language: r
sudo: required
cache: packages

r_packages:
 - devtools
 - RcolorBrewer
 - reshape2

install:
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_github('ivyleavedtoadflax/bookdown')"
  - Rscript -e "if (!require('RcolorBrewer')) install.packages('RColorBrewer')"
  - Rscript -e "if (!require('reshape2')) install.packages('reshape2')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
