language: r
sudo: required
cache: packages

r_packages:
 - devtools
 - RcolorBrewer

# For some reason the below does not work, need to specify
# the install manually using Rscript
#r_github_packages:
# - ivyleavedtoadflax/bookdown

install:
 - Rscript -e "devtools::install_github('ivyleavedtoadflax/bookdown')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
