language: r
sudo: required
cache: packages

install:
 - Rscript -e "if (!require('devtools')) install.packages('devtools')"
 - Rscript -e "devtools::install_github('ivyleavedtoadflax/bookdown')"
 - Rscript -e "if (!require('bookdown')) install.packages('bookdown')"
 - Rscript -e "if (!require('RColorBrewer')) install.packages('RColorBrewer')"
# - Rscript -e "if (!require('agricolae')) install.packages('agricolae')"

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
